spring:
  profiles:
    active:
      dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  cache:
    type: jcache
    jcache:
      config: classpath:ehcache-${spring.profiles.active}.xml

logging:
  config: classpath:logback-${spring.profiles.active}.xml